drop table if exists public.rel_submission_criteria;
create table public.rel_submission_criteria
(
    id            integer generated by default as identity
        constraint rel_submission_criteria_pk
            primary key,
    submission_id integer not null
        constraint rel_submission_criteria_trx_submission_id_fk
            references public.trx_submission
            on update cascade on delete cascade,
    criteria_id   integer not null
        constraint rel_submission_criteria_mst_criteria_id_fk
            references public.mst_criteria
            on update cascade on delete cascade,
    value         numeric
);

alter table public.rel_submission_criteria
    owner to postgres;


