drop table if exists public.mst_criteria;
create table public.mst_criteria
(
    id        integer generated by default as identity
        constraint mst_criteria_pk
            primary key,
    name      varchar(100) not null,
    score     numeric default 0,
    is_active boolean default true,
    "order"   numeric
);

alter table public.mst_criteria
    owner to postgres;

create index mst_criteria_name_index
    on public.mst_criteria (name);


