drop table if exists public.app_user;
create table public.app_user
(
    id                integer generated by default as identity
        constraint app_user_pk
            primary key,
    email             varchar(100) not null,
    name              varchar(100) not null,
    password          text         not null,
    user_type         varchar(20)  not null,
    status            varchar(20)  not null,
    created_at        timestamp(6) default CURRENT_TIMESTAMP,
    updated_at        timestamp(6),
    deleted_at        timestamp(6),
    last_logged_in_at timestamp(6)
);

alter table public.app_user
    owner to postgres;

create unique index app_user_email_uindex
    on public.app_user (email);

create index app_user_name_index
    on public.app_user (name);

create index app_user_status_index
    on public.app_user (status);

