drop table if exists public.mst_lecture;
create table public.mst_lecture
(
    id               integer generated by default as identity
        constraint mst_lecture_pk
            primary key,
    nip              varchar(12)  not null,
    name             varchar(100) not null,
    email            varchar(100) not null,
    study_program_id integer      not null
        constraint mst_lecture_mst_study_program_id_fk
            references public.mst_study_program
            on update cascade on delete cascade,
    created_at       timestamp(6) default CURRENT_TIMESTAMP,
    updated_at       timestamp(6)
);

alter table public.mst_lecture
    owner to postgres;

create unique index mst_lecture_email_uindex
    on public.mst_lecture (email);

create unique index mst_lecture_nip_uindex
    on public.mst_lecture (nip);

