drop table if exists public.trx_spk;
create table public.trx_spk
(
    id            integer generated by default as identity
        constraint trx_spk_pk
            primary key,
    period_id     integer not null
        constraint trx_spk_trx_submission_period_id_fk
            references public.trx_submission_period,
    submission_id integer
        constraint trx_spk_trx_submission_id_fk
            references public.trx_submission,
    rank          integer not null,
    preference_value          numeric not null,
    criteria          json not null,
    processed_at  timestamp default CURRENT_TIMESTAMP,
    processed_by  json
);

alter table public.trx_spk
    owner to postgres;

