drop table if exists public.mst_study_program;
create table public.mst_study_program
(
    id         integer generated by default as identity
        constraint mst_study_program_pk
            primary key,
    faculty_id integer              not null
        constraint mst_study_program_mst_faculty_id_fk
            references public.mst_faculty,
    name       varchar(100)         not null,
    is_active  boolean default true not null
);

alter table public.mst_study_program
    owner to postgres;

create index mst_study_program_is_active_index
    on public.mst_study_program (is_active);

create index mst_study_program_name_index
    on public.mst_study_program (name);




