drop table if exists public.mst_faculty;
create table public.mst_faculty
(
    id        integer generated by default as identity
        constraint mst_faculty_pk
            primary key,
    name      varchar(100) not null,
    is_active boolean default true
);

alter table public.mst_faculty
    owner to postgres;

create index mst_faculty_name_index
    on public.mst_faculty (name);

create index mst_faculty_is_active_index
    on public.mst_faculty (is_active);





