drop table if exists public.rel_user_role;
create table public.rel_user_role
(
    id        integer generated by default as identity
        constraint rel_user_role_pk
            primary key,
    user_id   integer     not null
        constraint rel_user_role_app_user_id_fk
            references public.app_user
            on update cascade on delete cascade,
    role_code varchar(10) not null
        constraint rel_user_role_app_role_code_fk
            references public.app_role
            on update cascade on delete cascade
);

alter table public.rel_user_role
    owner to postgres;


