DROP TABLE IF EXISTS "public"."rel_submission_criteria";
CREATE TABLE "public"."rel_submission_criteria" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "submission_id" int4 NOT NULL,
  "criteria_id" int4 NOT NULL,
  "value" numeric NOT NULL,
  CONSTRAINT "rel_submission_criteria_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "rel_submission_criteria-criteria_id-fk" FOREIGN KEY ("criteria_id") REFERENCES "public"."mst_criteria" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "rel_submission_criteria-submission_id-fk" FOREIGN KEY ("submission_id") REFERENCES "public"."trx_submission" ("id") ON DELETE CASCADE ON UPDATE CASCADE
)
;

ALTER TABLE "public"."rel_submission_criteria"
  OWNER TO "postgres";