DROP TABLE IF EXISTS "public"."mst_faculty" CASCADE;
CREATE TABLE "public"."mst_faculty" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "xid" uuid NOT NULL,
  "name" varchar(85) COLLATE "pg_catalog"."default" NOT NULL,
  "version" int4 DEFAULT 1,
  "modified_by" json,
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6),
  CONSTRAINT "mst_faculty_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."mst_faculty"
  OWNER TO "postgres";

CREATE INDEX "mst_faculty-name-idx" ON "public"."mst_faculty" USING btree (
  "name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE UNIQUE INDEX "mst_faculty-xid-uq" ON "public"."mst_faculty" USING btree (
  "xid" "pg_catalog"."uuid_ops" ASC NULLS LAST
);