DROP TABLE IF EXISTS "public"."mst_lecture";
CREATE TABLE "public"."mst_lecture" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "xid" int4 NOT NULL,
  "nip" varchar(12) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "email" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "version" int4,
  "modified_by" json,
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6),
  CONSTRAINT "mst_lecture_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."mst_lecture"
  OWNER TO "postgres";

CREATE UNIQUE INDEX "mst_lecture-email-uq" ON "public"."mst_lecture" USING btree (
  "email" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE INDEX "mst_lecture-name-idx" ON "public"."mst_lecture" USING btree (
  "name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE INDEX "mst_lecture-nip-idx" ON "public"."mst_lecture" USING btree (
  "nip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE INDEX "mst_lecture-xid-idx" ON "public"."mst_lecture" USING btree (
  "xid" "pg_catalog"."int4_ops" ASC NULLS LAST
);