DROP TABLE IF EXISTS "public"."trx_submission";
CREATE TABLE "public"."trx_submission" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "student_id" int4 NOT NULL,
  "entry_period" varchar(10) COLLATE "pg_catalog"."default" NOT NULL,
  "semester" int4 NOT NULL,
  "class" varchar(255) COLLATE "pg_catalog"."default",
  "status" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "approved_by" json,
  "approved_at" timestamp(6),
  "version" int4,
  "modified_by" json,
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6),
  CONSTRAINT "trx_submission_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "trx_submission-student_id-fk" FOREIGN KEY ("student_id") REFERENCES "public"."mst_student" ("id") ON DELETE CASCADE ON UPDATE CASCADE
)
;

ALTER TABLE "public"."trx_submission"
  OWNER TO "postgres";

CREATE INDEX "trx_submission-status-idx" ON "public"."trx_submission" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

COMMENT ON COLUMN "public"."trx_submission"."approved_by" IS 'keys: id, name, reason';