DROP TABLE IF EXISTS "public"."mst_reference";
CREATE TABLE "public"."mst_reference" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "type" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "value" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "is_active" bool NOT NULL DEFAULT true,
  CONSTRAINT "mst_reference_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."mst_reference"
  OWNER TO "postgres";

CREATE INDEX "mst_reference-name-idx" ON "public"."mst_reference" USING btree (
  "name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE UNIQUE INDEX "mst_reference-type-value-uq" ON "public"."mst_reference" USING btree (
  "type" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "value" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);