DROP TABLE IF EXISTS "public"."mst_student";
CREATE TABLE "public"."mst_student" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "xid" uuid NOT NULL,
  "nim" varchar(12) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "email" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "faculty_id" int4 NOT NULL,
  "study_program_id" int4 NOT NULL,
  "version" int4,
  "modified_by" json,
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6),
  CONSTRAINT "mst_student_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "mst_student-faculty_id-fk" FOREIGN KEY ("faculty_id") REFERENCES "public"."mst_faculty" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "mst_student-study_program_id-fk" FOREIGN KEY ("study_program_id") REFERENCES "public"."mst_study_program" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
)
;

ALTER TABLE "public"."mst_student"
  OWNER TO "postgres";

CREATE UNIQUE INDEX "mst_student-email-uq" ON "public"."mst_student" USING btree (
  "email" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE INDEX "mst_student-name-idx" ON "public"."mst_student" USING btree (
  "name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE INDEX "mst_student-nim-idx" ON "public"."mst_student" USING btree (
  "nim" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE INDEX "mst_student-xid-idx" ON "public"."mst_student" USING btree (
  "xid" "pg_catalog"."uuid_ops" ASC NULLS LAST
);