DROP TABLE IF EXISTS "public"."mst_program_study" CASCADE;
CREATE TABLE "public"."mst_program_study" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "xid" uuid NOT NULL,
  "name" varchar(85) COLLATE "pg_catalog"."default" NOT NULL,
  "faculty_id" int4,
  "version" int4,
  "modified_by" json,
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(6),
  CONSTRAINT "mst_program_study_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "mst_program_study-faculty_id-fk" FOREIGN KEY ("faculty_id") REFERENCES "public"."mst_faculty" ("id") ON DELETE NO ACTION ON UPDATE CASCADE
)
;

ALTER TABLE "public"."mst_program_study"
  OWNER TO "postgres";

CREATE INDEX "mst_program_study-name-idx" ON "public"."mst_program_study" USING btree (
  "name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

CREATE UNIQUE INDEX "mst_program_study-xid-idx" ON "public"."mst_program_study" USING btree (
  "xid" "pg_catalog"."uuid_ops" ASC NULLS LAST
);