import { mapEnumToTypes } from '@util/helpers';

enum TYPES_ENUM {
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',
  ENTITY_MANAGER = 'ENTITY_MANAGER',
  LOGGER = 'LOGGER',
  MINIO_INSTANCE = 'MINIO_INSTANCE',

  AUTH_SERVICE = 'AUTH_SERVICE',
  MINIO_SERVICE = 'MINIO_SERVICE',
  SUBMISSION_SERVICE = 'SUBMISSION_SERVICE',

  MST_FACULTY_REPOSITORY = 'MST_FACULTY_REPOSITORY',
  MST_STUDY_PROGRAM_REPOSITORY = 'MST_STUDY_PROGRAM_REPOSITORY'
}
const TYPES = mapEnumToTypes(TYPES_ENUM);
export default TYPES;
