import { mapEnumToTypes } from '@util/helpers';

enum TYPES_ENUM {
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',
  ENTITY_MANAGER = 'ENTITY_MANAGER',
  LOGGER = 'LOGGER',
  MINIO_INSTANCE = 'MINIO_INSTANCE',

  AUTH_SERVICE = 'AUTH_SERVICE',
  MINIO_SERVICE = 'MINIO_SERVICE',
  SUBMISSION_SERVICE = 'SUBMISSION_SERVICE',
  DOCUMENT_SERVICE = 'DOCUMENT_SERVICE',

  FACULTY_REPOSITORY = 'FACULTY_REPOSITORY',
  STUDY_PROGRAM_REPOSITORY = 'STUDY_PROGRAM_REPOSITORY',
  SUBMISSION_PERIOD_REPOSITORY = 'SUBMISSION_PERIOD_REPOSITORY',
  SUBMISSION_REPOSITORY = 'SUBMISSION_REPOSITORY',
  VIEW_SPK_RESULT_REPOSITORY = 'VIEW_SPK_RESULT_REPOSITORY',

  SCHEDULER = 'SCHEDULER'
}
const TYPES = mapEnumToTypes(TYPES_ENUM);
export default TYPES;
