import { mapEnumToConst } from '@util/helpers';

export enum VALIDATION_ENUM {
  SPECIFIC_EMAIL_DOMAIN = 'SPECIFIC_EMAIL_DOMAIN',
  INVALID_EXTENSION = 'INVALID_EXTENSION',
  REQUIRED_FILE = 'REQUIRED_FILE',
  INVALID_END_DATE = 'INVALID_END_DATE',
  INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
  INVALID_PARAM = 'INVALID_PARAM',
  INVALID_ORDER_PARAM = 'INVALID_ORDER_PARAM',
}
const VALIDATION = mapEnumToConst(VALIDATION_ENUM);
export default VALIDATION;